### PR TITLE
Changes to add new table & view to hold RAWS data

### PR DESCRIPTION
**Pull request by sneha-nagole**

### CODE REVIEW

**Review by DreamWver — APPROVED** [review]
Looks good.

**Review by comeara — APPROVED** [review]
👍

**Comment by comeara** [comment]
The change seems good as-is. How are we going to apply this to all the environments?

**Comment by sneha-nagole** [comment]
For now it is going to be manual part of release instructions. If you are referring to using migrations, we can work on it part of future JIRAs.

**Comment by comeara** [comment]
There are a few places that refer to database changes:

1. The `createdbs` script in the root of `nics-docker` repo
1. The documentation in the wiki of the `nics-common` repo
1. The `changes` directory of this `nics-db` repo

The last is a partial attempt at migrations implemented in the original fork.

I'd say that, at the least, we need to make sure that everyone knows how to change their local dev, new environments get these changes and the deployment procedures are documented for itest, training, staging and prod.

**Pull request merged**
